/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "just a week ago, this mysterious company had offered you a job. \"we have found recently that you have amazing potential,\" the letter they sent you said, \"you have special abilities that no one else has, and that you do not know you possess.\"": "就在一周前，这家神秘的公司给了你一份工作。 “我们最近发现你有惊人的潜力，”他们寄给你的信中说，“你拥有别人没有的特殊能力，而且你不知道自己拥有。”",
    "\"i mean. what's the worst that could happen?\"": "“我的意思是，可能发生的最坏的情况是什么？”",
    "\"what is this place...\" you wonder.": "“这是什么地方……”你想知道。",
    "about": "关于",
    "and that is how you begin producing massive amounts of a mysterious substance you know almost nothing about just to pay the bills.": "这就是你开始生产大量你几乎一无所知的神秘物质的方式，只是为了支付账单。",
    "autobuyer": "自动购买者",
    "boosts": "提升",
    "buy max": "购买最大",
    "dimension": "维度",
    "dimensions": "维度",
    "each dimension you buy increases the production of that dimension by (n+1/n)^(1/(n+2)), where n is the dimension number.": "您购买的每个维度都会将该维度的产量增加 (n+1/n)^(1/(n+2))，其中 n 是维度编号。",
    "help": "帮助",
    "locked": "未解锁",
    "max": "最大限度",
    "milestones": "里程碑",
    "off": "关闭",
    "press the '2 S' button to start!": "按“2 S”按钮开始！",
    "price": "价格",
    "story": "故事",
    "suddenly, the screen lights up.": "突然，屏幕亮了。",
    "toggle autobuyers:": "切换自动购买者：",
    "total (bought)": "总计（已购买）",
    "yoon seoyeon, you have chosen to become the first big S, or S1. out of many small s in the world, you are the first girl we discovered with the special ability to make S, a special kind of energy with supernatural properties.": "yoon seoyeon，你选择了成为第一个大S，或者说S1。 在世界上众多的小S中，你是我们发现的第一个具有制造S的特殊能力的女孩，S是一种具有超自然属性的特殊能量。",
    "you enter the mysterious room. no one else is there, just you...and a big blank screen.": "你进入神秘的房间。 那里没有其他人，只有你……和一个大的空白屏幕。",
    "you had been given instructions to go into the room on your first day at the new company, MODHAUS.": "你在新公司 MODHAUS 的第一天就被指示进入房间。",
    "you had been studying to retake the suneung. but of course, desperate to escape your mundane school life, you decided to leave and join this shady company instead.": "你一直在学习夺回suneung。 但是，当然，为了逃避平凡的学校生活，你决定离开并加入这家阴暗的公司。",
    "been equipped with 2 S. these 2 S are very valuable and rare, but they will no longer be rare when we start mass producing them.": "装备了2S，这2 S非常珍贵，也很稀有，但是当我们开始量产的时候，它们就不再稀有了。",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "your job now is to generate as much S as possible. click the 'S1' button to spend 2 S to buy your first dimension.": "你现在的工作是产生尽可能多的S。 单击“S 1”按钮花费 2 S 购买您的第一个维度。",
    "most dimensions usually produce the dimension one tier below them (S3 dimensions produce S2 dimensions, etc.) but S1 dimensions produce S, a special kind of energy with supernatural properties. buying a dimension also multiplies the dimension's overall production by 25/24.": "大多数维度通常会产生比它们低一级的维度（S3维度产生S2维度等），但S1维度产生S，一种具有超自然属性的特殊能量。 购买一个维度也会将该维度的总产量乘以 25/24。",
    ", developer of": "，开发者",
    "\"a perfect cure for alzheimer's\"": "“阿尔茨海默氏症的完美治疗方法”",
    "\"byte for now\"": "\“现在字节\”",
    "\"can i buy a house?\"": "“我可以买房子吗？”",
    "\"capitalism...\"": "\“资本主义...\”",
    "\"i really like sexy women\"": "“我真的很喜欢性感的女人”",
    "\"i thought chickens had 4 legs...\"": "“我以为鸡有 4 条腿……”",
    "\"ijbol\"": "“伊博尔”",
    "\"is this how it feels to partake in teaching practice sessions?\"": "“这就是参加教学实习的感觉吗？”",
    "\"isn't 24 too many?\"": "“24是不是太多了？”",
    "\"it's tiring to leave the haus...\"": "“离开家真累……”",
    "\"my evaluation is going to be electrocuted!\"": "“我的评价要触电了！”",
    "\"oh lol\"": "“哦哈哈”",
    "\"siblings with jiwoo (and hyerin is the dog)\"": "“和智宇是兄弟姐妹（惠潾是狗）”",
    "\"that scared me...\"": "\“这把我吓坏了...\”",
    "\"welcome to my kpop class!\"": "“欢迎来到我的韩流课！”",
    "\"you know, i used to play ice hockey...\"": "“你知道，我以前打冰球……”",
    "(thank you for helping me with my CSS)": "（感谢您帮助我处理 CSS）",
    "/challenges": "/挑战",
    "/credits": "/学分",
    "/objekts": "/对象",
    "10 event gravity challenges": "10项重力挑战",
    "additionally, for every dimension you buy, you increase the production by 1/24 (exponentially).": "此外，每购买一个尺寸，产量就会增加 1/24（指数）。",
    "all of these concepts in general: antimatter dimensions and FE000000": "所有这些一般概念：反物质维度和 FE000000",
    "and": "和",
    "apprehensively, you press the little button labeled \"S1\". suddenly, a machine appears in front of you.": "你忧心忡忡地按下了标有“S1”的小按钮。 突然，一台机器出现在你面前。",
    "at the moment, there is only one category of challenges, grand gravity challenges (gdgcs). these challenges require you to start from the beginning and cause a grand gravity but under limited circumstances. see": "目前，只有一类挑战，即大重力挑战（GDGCS）。 这些挑战要求你从头开始，并在有限的情况下引起巨大的引力。 看",
    "basics": "基本",
    "buy one S1 como dimension.": "购买一台 S1 como 尺寸。",
    "buy one S1 S dimension.": "购买一台 S1 S 尺寸。",
    "buy one S8 como dimension.": "购买一台 S8 como 尺寸。",
    "buy one S8 S dimension.": "购买一台 S8 S 尺寸。",
    "canaris": "金丝雀",
    "challenges": "挑战",
    "como": "科莫",
    "como dimensions work like S dimensions, but they produce comodust, not como (which is only obtainable from grand gravity). comodust is used to boost S1's overall production by (comodust)^0.125.": "科莫维度的工作方式与 S 维度类似，但它们产生科莫尘，而不是科莫（只能从大重力中获得）。 comodust 用于将 S1 的整体产量提高 (comodust)^0.125。",
    "concept": "概念",
    "credits": "学分",
    "dan simon (creator of FE000000)": "丹·西蒙（FE000000 的创造者）",
    "do 24 grand gravities.": "做24次大重力。",
    "do one grand gravity.": "做一场伟大的重力。",
    "each S1 dimension allows you to produce 0.001 S per millisecond. this number may increase over time, but what's important now is that you get as many dimensions as possible to produce S.": "每个 S1 维度允许您每毫秒产生 0.001 S。 这个数字可能会随着时间的推移而增加，但现在重要的是你获得尽可能多的维度来产生 S。",
    "each subsequent big S generates dimensions of the previous big S. for example, S3 dimensions will generate S2 dimensions, which in turn generate S1 dimensions, which generate S. this allows your S production to increase exponentially.": "随后的每个大S都会生成前一个大S的维度。例如，S3维度将生成S2维度，S2维度又生成S1维度，S1维度生成S。这使您的S产量呈指数级增长。",
    "faq": "常问问题",
    "finish all grand gravity challenges.": "完成所有重大重力挑战。",
    "finish four grand gravity challenges.": "完成四项重大重力挑战。",
    "for more.": "了解更多。",
    "game ideas": "游戏创意",
    "gdgc 5: FE000000 challenge 5": "GDGC 5：FE000000 挑战 5",
    "gdgc 7, 8: AD challenge 12": "GDGC 7、8：AD 挑战 12",
    "grand gravity": "大重力",
    "gravity": "重力",
    "hevipelle and all the other contributors to antimatter dimensions": "海维佩勒和所有其他反物质维度的贡献者",
    "how does saving work?": "储蓄如何运作？",
    "info on tripleS": "有关 TripS 的信息",
    "kaede and dahyun will be added": "枫和多贤将被添加",
    "keep generating S until you are able to unlock more members.": "不断生成S，直到您能够解锁更多成员。",
    "kuiper": "柯伊伯",
    "minn (@purplelit_ on discord)": "minn（discord 上的@purplelit_）",
    "MODHAUS on medium": "莫德豪斯 中等",
    "multipliers": "乘数",
    "multipliers boost S1's production in most cases (other than some challenges like gdgc6). the main multipliers you will notice are 8^(number of S - 1) and 24^(number of S8 dimensions).": "在大多数情况下，乘数都会提高 S1 的产量（gdgc6 等一些挑战除外）。 您会注意到的主要乘数是 8^（S - 1 的数量）和 24^（S8 维度的数量）。",
    "objekt either unlock (100) or boost (101-108) your autobuyers. your autobuyer interval starts at 256s, before halving with every objekt (other than 100). with all objekts, your autobuyer interval should be 1s. see": "objekt 解锁 (100) 或提升 (101-108) 您的自动购买者。 您的自动购买间隔从 256 秒开始，然后每个对象（100 除外）减半。 对于所有对象，您的自动购买间隔应为 1 秒。 看",
    "objekts": "对象",
    "part 1": "第 1 部分",
    "people": "人",
    "sapph": "萨夫",
    "second prestige layer (event gravity)": "第二声望层（事件重力）",
    "sigma dimensions": "西格玛维度",
    "source": "源",
    "the concept of this game was based on antimatter dimensions, a game where each dimension creates the previous dimension. i wanted to make a tripleS parody so here it is! for credits, see": "该游戏的概念基于反物质维度，即每个维度都会创建前一个维度的游戏。 我想做一个 TripleS 模仿，所以就在这里！ 对于学分，请参阅",
    "the first prestige layer. S is limted at 24^24, at which a grand gravity will occur. all gravity will be reset and one objekt and 2^(number of grand gravities including this one) como will be given.": "第一声望层。 S 被限制在 24^24，此时会产生巨大的引力。 所有重力将被重置，并给出 1 个物体和 2^(包括这个在内的大重力数) como。",
    "the WAV community (that has supported me and my projects since the start)": "WAV 社区（从一开始就支持我和我的项目）",
    "to view all your objekts.": "查看您的所有对象。",
    "tripleS": "三重S",
    "tripleS (for inspiring me to make this parody)": "TripleS（激励我制作这个模仿作品）",
    "WAV supporters": "WAV 支持者",
    "wav.haus": "瓦夫豪斯",
    "what are some future plans for the next minor/major update?": "下一次小/主要更新的未来计划是什么？",
    "when you have 4 S, you will be able to introduce another big S into the room. the second big S (S2) will not generate S, but is equipped with a dimension that generates your dimensions.": "当你有了4S，你就可以引入另一个大S进入房间。 第二个大S（S2）不会生成S，但配备有生成你的维度的维度。",
    "you got a new milestone: welcome to my kpop class!": "你有了一个新的里程碑：欢迎来到我的韩流课程！",
    "you must unlock and buy each S in order. for example, S3 cannot be bought unless you have at least one S2 dimension.": "您必须按顺序解锁并购买每个 S。 例如，除非您至少有一个 S2 维度，否则无法购买 S3。",
    "\"b-but,\" she stutters, \"who are you? and why are we here? how did you find us?\"": "“但、但是，”她结结巴巴地说，“你是谁？我们为什么在这里？你是怎么找到我们的？”",
    "and with that, the screen goes blank again.": "然后，屏幕再次变成空白。",
    "colors": "颜色",
    "export": "导出",
    "hard reset": "硬重置",
    "i will see you then.": "我们稍后见。",
    "import": "导入",
    "jeong hyerin, you have been chosen to become the second big S, or S2. out of many small s in the world, you are the second girl we discovered with the special ability to make S.": "郑惠潾，你被选为第二个大S，或者说S2。 在世界上众多小S中，你是我们发现的第二个具有制造S特殊能力的女孩。",
    "members": "会员",
    "my name is SUAH. we at MODHAUS searched far and wide through years and years of extensive research to find 24 special girls who have the special ability. you two are just the first two.": "我的名字是苏阿。 我们 MODHAUS 通过多年的广泛研究，广泛搜寻，找到了 24 名拥有特殊能力的特殊女孩。 你们两个只是前两个。",
    "on": "开启",
    "options": "选项",
    "reset": "重置",
    "save": "保存",
    "save to file": "保存到文件",
    "you press the \"S2\" button. suddenly, another girl comes in and sits down next to you. the screen then lights up again.": "您按下“S2”按钮。 突然，另一个女孩进来并坐在你旁边。 然后屏幕再次亮起。",
    "your data will be automatically saved. offline progress is not supported.": "您的数据将被自动保存。 不支持离线进度。",
    "your job now is to generate as many S1 dimensions as possible. with yoon seoyeon, or S1, you will soon unlock 6 other S.": "你现在的工作是生成尽可能多的 S1 维度。 有了 yoon seoyeon（即 S1），您很快就会解锁其他 6 个 S。",
    "your purpose will soon be made clear.": "你的目的很快就会明确。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "you have ": "你有 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) S.$/,
    /^([\d\.]+) S. \(([\d\.]+) S\/s\)$/,
    /^([\d\.]+) S. \(([\d\.]+)\/([\d\.]+) S\/s\)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+) S.$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^get all S([\d\.,]+) Atom([\d\.,]+) objekts.$/, '获取所有 S$1 原子$2 对象。'],
    [/^gdgc ([\d\.,]+): AD challenge ([\d\.,]+)$/, 'gdgc $1: 反物质维度 挑战 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) como.$/, '$1 como.'],
    [/^chapter ([\d\.,]+)$/, '章节 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);