/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "just a week ago, this mysterious company had offered you a job. \"we have found recently that you have amazing potential,\" the letter they sent you said, \"you have special abilities that no one else has, and that you do not know you possess.\"": "就在一周前，这家神秘的公司给了你一份工作。 “我们最近发现你有惊人的潜力，”他们寄给你的信中说，“你拥有别人没有的特殊能力，而且你不知道自己拥有。”",
    "\"i mean. what's the worst that could happen?\"": "“我的意思是，可能发生的最坏的情况是什么？”",
    "\"what is this place...\" you wonder.": "“这是什么地方……”你想知道。",
    "about": "关于",
    "and that is how you begin producing massive amounts of a mysterious substance you know almost nothing about just to pay the bills.": "这就是你开始生产大量你几乎一无所知的神秘物质的方式，只是为了支付账单。",
    "autobuyer": "自动购买者",
    "boosts": "提升",
    "buy max": "购买最大",
    "dimension": "维度",
    "dimensions": "维度",
    "each dimension you buy increases the production of that dimension by (n+1/n)^(1/(n+2)), where n is the dimension number.": "您购买的每个维度都会将该维度的产量增加 (n+1/n)^(1/(n+2))，其中 n 是维度编号。",
    "help": "帮助",
    "locked": "未解锁",
    "max": "最大",
    "milestones": "里程碑",
    "off": "关闭",
    "press the '2 S' button to start!": "按“2 S”按钮开始！",
    "price": "价格",
    "story": "故事",
    "suddenly, the screen lights up.": "突然，屏幕亮了。",
    "toggle autobuyers:": "切换自动购买者：",
    "total (bought)": "总计（已购买）",
    "yoon seoyeon, you have chosen to become the first big S, or S1. out of many small s in the world, you are the first girl we discovered with the special ability to make S, a special kind of energy with supernatural properties.": "yoon seoyeon，你选择了成为第一个大S，或者说S1。 在世界上众多的小S中，你是我们发现的第一个具有制造S的特殊能力的女孩，S是一种具有超自然属性的特殊能量。",
    "you enter the mysterious room. no one else is there, just you...and a big blank screen.": "你进入神秘的房间。 那里没有其他人，只有你……和一个大的空白屏幕。",
    "you had been given instructions to go into the room on your first day at the new company, MODHAUS.": "你在新公司 MODHAUS 的第一天就被指示进入房间。",
    "you had been studying to retake the suneung. but of course, desperate to escape your mundane school life, you decided to leave and join this shady company instead.": "你一直在学习夺回suneung。 但是，当然，为了逃避平凡的学校生活，你决定离开并加入这家阴暗的公司。",
    "been equipped with 2 S. these 2 S are very valuable and rare, but they will no longer be rare when we start mass producing them.": "装备了2S，这2 S非常珍贵，也很稀有，但是当我们开始量产的时候，它们就不再稀有了。",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "your job now is to generate as much S as possible. click the 'S1' button to spend 2 S to buy your first dimension.": "你现在的工作是产生尽可能多的S。 单击“S 1”按钮花费 2 S 购买您的第一个维度。",
    "most dimensions usually produce the dimension one tier below them (S3 dimensions produce S2 dimensions, etc.) but S1 dimensions produce S, a special kind of energy with supernatural properties. buying a dimension also multiplies the dimension's overall production by 25/24.": "大多数维度通常会产生比它们低一级的维度（S3维度产生S2维度等），但S1维度产生S，一种具有超自然属性的特殊能量。 购买一个维度也会将该维度的总产量乘以 25/24。",
    ", developer of": "，开发者",
    "\"a perfect cure for alzheimer's\"": "“阿尔茨海默氏症的完美治疗方法”",
    "\"byte for now\"": "\“现在字节\”",
    "\"can i buy a house?\"": "“我可以买房子吗？”",
    "\"capitalism...\"": "\“资本主义...\”",
    "\"i really like sexy women\"": "“我真的很喜欢性感的女人”",
    "\"i thought chickens had 4 legs...\"": "“我以为鸡有 4 条腿……”",
    "\"ijbol\"": "“伊博尔”",
    "\"is this how it feels to partake in teaching practice sessions?\"": "“这就是参加教学实习的感觉吗？”",
    "\"isn't 24 too many?\"": "“24是不是太多了？”",
    "\"it's tiring to leave the haus...\"": "“离开家真累……”",
    "\"my evaluation is going to be electrocuted!\"": "“我的评价要触电了！”",
    "\"oh lol\"": "“哦哈哈”",
    "\"siblings with jiwoo (and hyerin is the dog)\"": "“和智宇是兄弟姐妹（惠潾是狗）”",
    "\"that scared me...\"": "\“这把我吓坏了...\”",
    "\"welcome to my kpop class!\"": "“欢迎来到我的韩流课！”",
    "\"you know, i used to play ice hockey...\"": "“你知道，我以前打冰球……”",
    "(thank you for helping me with my CSS)": "（感谢您帮助我处理 CSS）",
    "/challenges": "/挑战",
    "/credits": "/学分",
    "/objekts": "/对象",
    "10 event gravity challenges": "10项重力挑战",
    "additionally, for every dimension you buy, you increase the production by 1/24 (exponentially).": "此外，每购买一个维度，产量就会增加 1/24（指数）。",
    "all of these concepts in general: antimatter dimensions and FE000000": "所有这些一般概念：反物质维度和 FE000000",
    "and": "和",
    "apprehensively, you press the little button labeled \"S1\". suddenly, a machine appears in front of you.": "你忧心忡忡地按下了标有“S1”的小按钮。 突然，一台机器出现在你面前。",
    "at the moment, there is only one category of challenges, grand gravity challenges (gdgcs). these challenges require you to start from the beginning and cause a grand gravity but under limited circumstances. see": "目前，只有一类挑战，即大重力挑战（GDGCS）。 这些挑战要求你从头开始，并在有限的情况下引起巨大的引力。 看",
    "basics": "基础",
    "buy one S1 como dimension.": "购买一个 S1 como 维度。",
    "buy one S1 S dimension.": "购买一个 S1 S 维度。",
    "buy one S8 como dimension.": "购买一个 S8 como 维度。",
    "buy one S8 S dimension.": "购买一个 S8 S 维度。",
    "canaris": "canaris",
    "challenges": "挑战",
    "como": "como",
    "como dimensions work like S dimensions, but they produce comodust, not como (which is only obtainable from grand gravity). comodust is used to boost S1's overall production by (comodust)^0.125.": "como维度的工作方式与 S 维度类似，但它们产生como尘埃，而不是como（只能从大重力中获得）。 como尘埃 用于将 S1 的整体产量提高 (como尘埃)^0.125。",
    "concept": "概念",
    "credits": "鸣谢",
    "dan simon (creator of FE000000)": "dan simon（FE000000 的创造者）",
    "do 24 grand gravities.": "做24次大重力。",
    "do one grand gravity.": "做一场伟大的重力。",
    "each S1 dimension allows you to produce 0.001 S per millisecond. this number may increase over time, but what's important now is that you get as many dimensions as possible to produce S.": "每个 S1 维度允许您每毫秒产生 0.001 S。 这个数字可能会随着时间的推移而增加，但现在重要的是你获得尽可能多的维度来产生 S。",
    "each subsequent big S generates dimensions of the previous big S. for example, S3 dimensions will generate S2 dimensions, which in turn generate S1 dimensions, which generate S. this allows your S production to increase exponentially.": "随后的每个大S都会生成前一个大S的维度。例如，S3维度将生成S2维度，S2维度又生成S1维度，S1维度生成S。这使您的S产量呈指数级增长。",
    "faq": "常问问题",
    "finish all grand gravity challenges.": "完成所有重大重力挑战。",
    "finish four grand gravity challenges.": "完成四项重大重力挑战。",
    "for more.": "了解更多。",
    "game ideas": "游戏创意",
    "gdgc 5: FE000000 challenge 5": "GDGC 5：FE000000 挑战 5",
    "gdgc 7, 8: AD challenge 12": "GDGC 7、8：AD 挑战 12",
    "grand gravity": "大重力",
    "gravity": "重力",
    "hevipelle and all the other contributors to antimatter dimensions": "hevipelle 和所有其他反物质维度的贡献者",
    "how does saving work?": "保存如何运作？",
    "info on tripleS": "有关 TripS 的信息",
    "kaede and dahyun will be added": "枫和多贤将被添加",
    "keep generating S until you are able to unlock more members.": "不断生成S，直到您能够解锁更多成员。",
    "multipliers": "乘数",
    "multipliers boost S1's production in most cases (other than some challenges like gdgc6). the main multipliers you will notice are 8^(number of S - 1) and 24^(number of S8 dimensions).": "在大多数情况下，乘数都会提高 S1 的产量（gdgc6 等一些挑战除外）。 您会注意到的主要乘数是 8^（S - 1 的数量）和 24^（S8 维度的数量）。",
    "objekt either unlock (100) or boost (101-108) your autobuyers. your autobuyer interval starts at 256s, before halving with every objekt (other than 100). with all objekts, your autobuyer interval should be 1s. see": "objekt 解锁 (100) 或提升 (101-108) 您的自动购买者。 您的自动购买间隔从 256 秒开始，然后每个对象（100 除外）减半。 对于所有对象，您的自动购买间隔应为 1 秒。 看",
    "objekts": "对象",
    "part 1": "第 1 部分",
    "people": "人员",
    "sapph": "萨夫",
    "second prestige layer (event gravity)": "第二声望层（事件重力）",
    "sigma dimensions": "西格玛维度",
    "source": "源码",
    "the concept of this game was based on antimatter dimensions, a game where each dimension creates the previous dimension. i wanted to make a tripleS parody so here it is! for credits, see": "该游戏的概念基于反物质维度，即每个维度都会创建前一个维度的游戏。 我想做一个 TripleS 模仿，所以就在这里！ 对于民协，请参阅",
    "the first prestige layer. S is limted at 24^24, at which a grand gravity will occur. all gravity will be reset and one objekt and 2^(number of grand gravities including this one) como will be given.": "第一声望层。 S 被限制在 24^24，此时会产生巨大的引力。 所有重力将被重置，并给出 1 个物体和 2^(包括这个在内的大重力数) como。",
    "the WAV community (that has supported me and my projects since the start)": "WAV 社区（从一开始就支持我和我的项目）",
    "to view all your objekts.": "查看您的所有对象。",
    "tripleS": "三重S",
    "tripleS (for inspiring me to make this parody)": "TripleS（激励我制作这个模仿作品）",
    "WAV supporters": "WAV 支持者",
    "wav.haus": "wav.haus",
    "what are some future plans for the next minor/major update?": "下一次小/主要更新的未来计划是什么？",
    "when you have 4 S, you will be able to introduce another big S into the room. the second big S (S2) will not generate S, but is equipped with a dimension that generates your dimensions.": "当你有了4S，你就可以引入另一个大S进入房间。 第二个大S（S2）不会生成S，但配备有生成你的维度的维度。",
    "you got a new milestone: welcome to my kpop class!": "你有了一个新的里程碑：欢迎来到我的韩流课程！",
    "you must unlock and buy each S in order. for example, S3 cannot be bought unless you have at least one S2 dimension.": "您必须按顺序解锁并购买每个 S。 例如，除非您至少有一个 S2 维度，否则无法购买 S3。",
    "\"b-but,\" she stutters, \"who are you? and why are we here? how did you find us?\"": "“但、但是，”她结结巴巴地说，“你是谁？我们为什么在这里？你是怎么找到我们的？”",
    "and with that, the screen goes blank again.": "然后，屏幕再次变成空白。",
    "colors": "颜色",
    "export": "导出",
    "hard reset": "硬重置",
    "i will see you then.": "我们稍后见。",
    "import": "导入",
    "jeong hyerin, you have been chosen to become the second big S, or S2. out of many small s in the world, you are the second girl we discovered with the special ability to make S.": "郑惠潾，你被选为第二个大S，或者说S2。 在世界上众多小S中，你是我们发现的第二个具有制造S特殊能力的女孩。",
    "members": "成员",
    "my name is SUAH. we at MODHAUS searched far and wide through years and years of extensive research to find 24 special girls who have the special ability. you two are just the first two.": "我的名字是苏阿。 我们 MODHAUS 通过多年的广泛研究，广泛搜寻，找到了 24 名拥有特殊能力的特殊女孩。 你们两个只是前两个。",
    "on": "开启",
    "options": "选项",
    "reset": "重置",
    "save": "保存",
    "save to file": "保存到文件",
    "you press the \"S2\" button. suddenly, another girl comes in and sits down next to you. the screen then lights up again.": "您按下“S2”按钮。 突然，另一个女孩进来并坐在你旁边。 然后屏幕再次亮起。",
    "your data will be automatically saved. offline progress is not supported.": "您的数据将被自动保存。 不支持离线进度。",
    "your job now is to generate as many S1 dimensions as possible. with yoon seoyeon, or S1, you will soon unlock 6 other S.": "你现在的工作是生成尽可能多的 S1 维度。 有了 yoon seoyeon（即 S1），您很快就会解锁其他 6 个 S。",
    "your purpose will soon be made clear.": "你的目的很快就会明确。",
    "general": "常规",
    "MODHAUS has created a fan-participatory governance system using blockchain technology in order to bring fans into the decision-making process. fans are given the opportunity to participate and communicate with the group by deciding the DIMENSIONs and the content through photocards called objekts and a currency called COMO.": "MODHAUS利用区块链技术创建了粉丝参与的治理系统，以便让粉丝参与决策过程。 粉丝有机会通过名为 objekts 的照片卡和名为 COMO 的货币来决定维度和内容，从而参与该团体并与该团体进行交流。",
    "each S, or member of the group, will be performing as a solo, as various subunits (DIMENSIONs), or as a team. each DIMENSION’s composition is determined through Gravity, or votes from fans.": "每个 S 或团体成员将作为独奏、各种子单元 (DIMENSION) 或团队进行表演。 每个 DIMENSION 的构成都是通过重力或粉丝的投票决定的。",
    "fan participation": "粉丝参与",
    "tripleS is a South Korean girl group formed by MODHAUS. the group is currently being introduced to the public through a pre-debut project that began in May 2022, where each of the 24 members are revealed periodically.": "TripleS是由MODHAUS组建的韩国女子组合。 该团体目前正在通过 2022 年 5 月开始的出道前项目向公众介绍，其中 24 名成员中的每一位都会定期被曝光。",
    "\"'prestige layer'...? this sounds like an idle game,\" chaeyeon remarks.": "“‘声望层’……？这听起来像是一个放置游戏，”彩妍评论道。",
    "\"ALRIGHT!\" you clasp your hands together, struggling to keep her own cool.": "“好吧！”你双手合十，努力让自己保持冷静。",
    "\"are you sure?\" soomin looks scared.": "“你确定吗？”soomin看起来很害怕。",
    "\"do any of you have matches? we might be able to burn the place down.\" jiwoo shouts.": "“你们有人有火柴吗？我们也许能把这个地方烧毁。”jiwoo 喊道。",
    "\"don't worry too much about that yet. SUAH will be coming in any minute...\" hyerin mutters.": "“先别太担心。SUAH 随时都会来……”惠琳嘀咕道。",
    "\"GUYS. CALM DOWN. WE'RE GOING TO LIVE. THEY PROBABLY WON'T KILL US HERE,\" you shout to calm everyone down.": "“伙计们，冷静点。我们要活下去。他们可能不会在这里杀我们。”你大喊着让大家平静下来。",
    "\"here goes nothing!\" you quickly press the \"S8\" button, and the eighth girl finally walks in.": "“没什么！”你快速按下“S8”按钮，第八个女孩终于走了进来。",
    "\"hi...uh...\" S8 walks in and waves shyly. \"my name's gong yubin. do you guys know why we're here?\"": "“嗨……呃……”S8走进来，害羞地挥手。 “我叫宫宇彬，你们知道我们为什么来这里吗？”",
    "\"I HAVE A BOX!\" yooyeon tosses her box of matches over.": "“我有一个盒子！”悠妍把她的火柴盒扔了过去。",
    "\"I WANT TO GO HOME!\" soomin screams.": "“我想回家！”soomin尖叫道。",
    "\"is no one going to talk about how she said that the S will combust?\" yubin's face is filled with worry.": "“没人说说她说的S会燃烧吗？”宇彬满脸担忧。",
    "\"look!\" hyerin points excitedly to the screen, \"we have enough to bring in S8!\"": "“看！”惠潾兴奋地指着屏幕，“我们已经足够带S8了！”",
    "\"oh its just ten quintillion,\" yooyeon quickly answers, \"nothing much.\"": "“哦，只有十亿亿，”柳渊很快回答道，“没什么。”",
    "\"SUAH? who's SUAH?\" jiwoo asks.": "“SUAH？SUAH是谁？”jiwoo问道。",
    "\"that's because it is.\" nakyoung deadpans.": "“那是因为它就是这样。”nakyoung 面无表情。",
    "\"we need to get out of here ASAP!\" hyerin darts a few hurried glances around the room, looking for an exit.": "“我们需要尽快离开这里！”慧琳快速地扫视了房间几圈，寻找出口。",
    "\"we need to stay here and finish all of this so we can get out. we're going to have to trust SUAH and MODHAUS on this one. now everyone get back to work!\"": "“我们需要留在这里完成这一切，这样我们才能出去。在这件事上我们必须相信 SUAH 和 MODHAUS。现在每个人都回去工作了！”",
    "\"what's... e19?\" soomin inquires.": "“什么是……e19？”秀民询问。",
    "\"yes. yes. no one is dying here. not under my watch.\"": "“是的。是的。这里没有人死去。不是在我的监视下。”",
    "\"you'll see.\" you sit the last girl down in front of the screen as it lights up once again.": "“你会看到的。”当屏幕再次亮起时，你让最后一个女孩坐在屏幕前。",
    "(increase of": "（增加",
    "), but all other dimensions will be reset to 0.": ")，但所有其他维度将重置为 0。",
    "*i will see you then.": "*我们稍后见。",
    "*right now, your task is to get to 1.333e33 S. such huge amounts of S are at the very limit of our capacity, so the S will combust and cause what is called a grand gravity, your first prestige layer. *": "*现在，你的任务是达到1.333e33 S。如此大量的S已经达到了我们能力的极限，因此S会燃烧并引起所谓的大重力，即你的第一个声望层。 *",
    "after minutes... or was it hours? you have no idea. you've lost track of time at this point.": "几分钟后……还是几小时后？ 你不知道。 此时你已经忘记了时间。",
    "anyway, after a bunch of grinding, you finally have nearly enough S to introduce S8 into the room, which the 7 of you have affectionately nicknamed the HAUS, despite it being a \"room\" and not a \"house\".": "不管怎样，经过一番磨练，你们终于有了差不多足够的S，可以把S8引入房间了，你们7个人亲切地昵称它为HAUS，尽管它是一个“房间”而不是“房子”。",
    "as i told seoyeon and hyerin earlier, we at MODHAUS searched far and wide through years and years of extensive research to find the 24 special girls who have the special ability to produce S.": "正如我之前告诉 Seoyeon 和 Hyerin 的那样，我们 MODHAUS 通过多年的广泛研究进行了广泛的搜索，以找到 24 名具有特殊能力的特殊女孩，她们能够产生 S。",
    "at the moment, we have only found the 8 of you, although many more are on the way.": "目前，我们只找到了你们八个人，尽管还有更多人正在路上。",
    "at this point, five other members have been revealed.\nS3 lee jiwoo,\nS4 kim chaeyeon,\nS5 kim yooyeon,\nS6 kim soomin,\nand S7 kim nakyoung.": "目前，其他五名成员已经公布。\nS3 lee jiwoo、\nS4 kim chaeyeon、\nS5 kim yooyeon、\nS6 kim soomin、\n和 S7 kim nakyoung。",
    "everyone takes in deep breaths to calm themselves down. jiwoo quickly puts her matches away.": "每个人都深吸一口气，让自己平静下来。 jiwoo 迅速收起火柴。",
    "greetings, seoyeon and hyerin. i see you have gathered the next 6 girls. good job.": "问候，瑞妍和慧琳。 我看到你已经聚集了接下来的 6 个女孩。 好工作。",
    "sacrifice": "牺牲",
    "the 7 of you have been hard at work, and have produced a lot of S in a rather short amount of time.": "你们7个人辛苦了，在很短的时间内就产出了很多S。",
    "to the other 6 of you, welcome. my name is SUAH, and i am an AI representative of MODHAUS, the secret organisation that has brought you all here.": "其他六位，欢迎。 我叫 SUAH，是 MODHAUS 的人工智能代表，这个秘密组织把你们带到了这里。",
    "when you sacrifice, your S8 dimensions will be boosted by": "当你牺牲时，你的S8维度将会增加",
    "you currently have a sacrifice bonus of": "你目前的牺牲奖励为",
    "you got a new milestone: byte for now": "你有了一个新的里程碑：现在是字节",
    "boom!": "轰！",
    "como.": "como。",
    "too much S!": "太多S了！",
    "when you grand gravity, you will lose all your dimensions and S for": "当你的重力很大时，你将失去所有的维度和S",
    "first thing you've unlocked is como. como will be used for another set of dimensions, and como progression will be much slower. these como dimensions will generate como power, which will boost your S production. you will also get (como power)^(1/24) como per second.": "你解锁的第一件事是como。 como 将用于另一组维度，并且 como 进度会慢得多。 这些 como 维度将产生 como 功率，这将提高您的 S 产量。 您还将获得每秒 (como power)^(1/24) como。",
    "the third thing you've unlocked is grand gravity challenges. finishing the first grand gravity was actually your first challenge, and you have completed it! the other 7 challenges boost your production, and to complete these, you will have to generate enough como for a grand gravity under harsh conditions. rewards for challenges also consist of one objekt and one como, of course.": "您解锁的第三件事是巨大的重力挑战。 完成第一个大重力实际上是你的第一个挑战，你已经完成了！ 其他 7 个挑战可以提高你的产量，为了完成这些挑战，你必须在恶劣的条件下产生足够的重力来满足巨大的重力。 当然，挑战的奖励也包括一件物品和一件COMO。",
    "\"interesting...\" you muse. \"so we need to do another...71 grand gravities before suah meets us again! EVERYBODY BACK TO WORK!\"": "“有趣……”你沉思道。 “所以在suah再次见到我们之前，我们需要再做一次……71个大重力！大家都回去工作了！”",
    "*congratulations on your first grand gravity. you have now unlocked multiple different things to boost your S production.": "*恭喜你获得第一个大重力。 您现在已经解锁了多个不同的东西来提高您的 S 产量。",
    "a drawer pops out of the wall.": "一个抽屉从墙上弹出。",
    "anyway, back to the new things you've unlocked with the first grand gravity.": "无论如何，回到你通过第一大重力解锁的新事物。",
    "boost challenge boost on S production": "提高S产量的挑战",
    "boost como gain": "提高COMO增益",
    "boost comodust boost on S production": "boost comodust 提高 S 产量",
    "boost comodust production": "提高玉米粉产量",
    "boost milestone boost on comodust production": "促进comodust产量的里程碑式增长",
    "boost objekt boost on S production": "提升 对象 提高 S 产量",
    "boost S dimensions": "增强S维度",
    "boost sacrifice boost on S production": "提高S生产的牺牲率",
    "chaeyeon grimaces. \"there's more...?\"": "彩妍做了个鬼脸。 \“还有更多...？\”",
    "each 100 objekt unlocks an autobuyer, and each other objekt speeds up the corresponding autobuyer.": "每 100 个 objekt 解锁一个自动购买器，每个其他 objekt 都会加速相应的自动购买器。",
    "each objekt also multiplies your sacrifice boost by": "每个物体也会使你的牺牲加成倍增",
    "here is two como and one objekt. with every grand gravity, you will be given one set of these, but your como doubles every grand gravity.": "这是两个 como 和一个 objekt。 每有一个大重力，你就会得到一套这些，但你的科莫会使每个大重力加倍。",
    "objekt": "对象",
    "single class": "单类",
    "the objekt is a very smooth laminated piece of paper with a picture of one of you on it, and feels like a trading card but slightly thicker. the como, meanwhile, are a bunch of shiny purple tokens.": "该物体是一张非常光滑的层压纸，上面印有你们中的一个人的照片，感觉就像一张交易卡，但稍厚一些。 与此同时，como 是一堆闪亮的紫色代币。",
    "the second thing you've unlocked are objekts. the first 8 objekts unlock autobuyers for each of your dimensions so that your work will be less manual. the other 64 autobuyers boost the speed of the respective S's autobuyer.": "你解锁的第二件事是物体。 前 8 个对象可为您的每个维度解锁自动购买者，以便您的工作减少手动操作。 其他 64 个自动购买者提高了各自 S 的自动购买者的速度。",
    "the smoke clears. the 8 of you emerge coughing, while the screen lights up again.": "烟雾散去。 你们八个人开始咳嗽，同时屏幕再次亮起。",
    "upgrades": "升级",
    "yes. after all, we still do not have all 24 girls yet.": "是的。 毕竟，我们还没有拥有全部 24 个女孩。",
    "you are not in any challenges.": "你没有遇到任何挑战。",
    "you got a new milestone: ijbol": "你有了一个新的里程碑：ijbol",
    "your new task is to get all 72 objekts and finish all 8 challenges. i will see you again then. but before i leave...": "你的新任务是获得全部 72 个物品并完成全部 8 个挑战。 到时候我会再次见到你。 但在我离开之前...",
    "all dimension costs change base from 2 to 3.": "所有维度成本的基数从 2 更改为 3。",
    "all dimensions get a random multiplier from x0.24 to 8.": "所有维度都有一个从 x0.24 到 8 的随机乘数。",
    "buying a dimension automatically erases all lower tier dimensions.": "购买维度会自动删除所有较低层的维度。",
    "dimension shift": "维度转换",
    "each challenge multiplies the production of the corresponding dimension by": "每个挑战都会将相应维度的产量乘以",
    "each dimension produces the dimension two tiers below. if not available, produces S.": "每个维度都会产生下面两层的维度。 如果不可用，则生成 S。",
    "each dimension produces the nearest lower-tier dimension in the same subunit. if not available, produces S.": "每个维度都会产生同一子单元中最接近的下层维度。 如果不可用，则生成 S。",
    "finished": "已完成",
    "first grand gravity": "第一大重力",
    "generation (smol ver.)": "世代（smol版本）",
    "it's gold? or white?": "是金子吗？ 还是白色？",
    "reach 24^24 for the first time.": "首次达到24^24。",
    "S1 dimension is heavily weakened but gets an exponentially increasing bonus.": "S1维度被严重削弱，但奖励却呈指数级增长。",
    "S7 and S8 dimensions are unavailable.": "S7 和 S8 尺寸不可用。",
    "start": "开始",
    "termination": "终止",
    "triplequarterS": "三季度",
    "two-system generation": "双系统生成",
    "two-system generation\n(DIMENSION ver.)": "双系统生成\n(DIMENSION ver.)",
    "you got 4 como and a S6 100 objekt.": "你有 4 个 COMO 和一个 S6 100 对象。",
    "you got a new milestone: my evaluation is going to be electrocuted!": "你又迎来了新的里程碑：我的评价是要触电了！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "kuiper": "kuiper",
    "minn (@purplelit_ on discord)": "minn（@purplelit_ 在 discord）",
    "MODHAUS on medium": "MODHAUS on medium",
    "NaN S.": "NaN S.",
    "s": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "设置",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "you have ": "你有 ",
    "each como dimension from S5 onwards multiplies the S limit by ": "从 S5 开始，每个 como 维度都将 S 限制乘以 ",
    "your comodust is boosting S production by ": "您的 como尘埃 正在通过以下方式提高 S 产量：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) S.$/,
    /^([\d\.]+) S. \(([\d\.]+) S\/s\)$/,
    /^([\d\.]+)e([\d\.,]+) S.$/,
    /^([\d\.]+)e([\d\.,]+) S. \(([\d\.]+)e([\d\.,]+) S\/s\)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+) S.$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) como and (.+) comodust.$/, '$1 como 和 $2 como尘埃.'],
    [/^(.+) como and (.+) comodust. \((.+) comodust\/s\)$/, '$1 como 和 $2 como尘埃. \($3 como尘埃\/秒\)'],
    [/^you got (.+) como and a S(.+) (.+) objekt.$/, '你得到了 $1 como 和一个 S$2 $3 对象。'],
    [/^get all S([\d\.,]+) Atom([\d\.,]+) objekts.$/, '获取所有 S$1 原子$2 对象。'],
    [/^gdgc ([\d\.,]+): AD challenge ([\d\.,]+)$/, 'gdgc $1: 反物质维度 挑战 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) como.$/, '$1 como.'],
    [/^chapter ([\d\.,]+)$/, '章节 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);